---
- name: common install
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - vim
    - curl

- name: mackerel get
  get_url: url=https://mackerel.io/assets/files/scripts/setup-apt.sh dest=/usr/local/src mode=755

- name: mackerel install
  command: /usr/local/src/setup-apt.sh

- name: updates a server
  apt: update_cache=yes

- name: upgrade a server
  apt: upgrade=full

- name: common install
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mackerel-agent
    - mackerel-agent-plugins

- name: copy mackerel.conf
  template: src=mackerel-agent.conf.j2 dest=/etc/mackerel-agent/mackerel-agent.conf
  notify:
    - restart mackerel

- name: start mackerel
  action: service name=mackerel-agent state=started

